// <auto-generated />
using System;
using CrudPessoaEndereco.PessoaAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudPessoaEndereco.PessoaAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220731220434_seedDb")]
    partial class seedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CadastroPessoaEndereco.PessoaAPI.Model.Endereco", b =>
                {
                    b.Property<Guid>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("EnderecoId");

                    b.Property<string>("Bairro")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("Cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Cidade");

                    b.Property<string>("EstadoUf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Estado");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Numero");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("char(36)");

                    b.HasKey("EnderecoId");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Endereco");

                    b.HasData(
                        new
                        {
                            EnderecoId = new Guid("0020a95c-9b37-4bbe-a017-6d658e3dd0d2"),
                            Bairro = "Farol",
                            Cep = "49032490",
                            Cidade = "Farolandia",
                            EstadoUf = "SE",
                            Logradouro = "av.murilo dantas",
                            Numero = "1155",
                            PessoaId = new Guid("e377f741-b75e-4fab-8a51-1af9c01a6a95")
                        },
                        new
                        {
                            EnderecoId = new Guid("6be645b6-4bb6-4206-a0b8-ad211f25e2da"),
                            Bairro = "Coqueiros",
                            Cep = "5512460",
                            Cidade = "Barra",
                            EstadoUf = "SE",
                            Logradouro = "av.dantas",
                            Numero = "1157",
                            PessoaId = new Guid("26f753a5-6ed9-45b0-95c1-9113148e6e1d")
                        });
                });

            modelBuilder.Entity("CadastroPessoaEndereco.PessoaAPI.Model.Pessoa", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("PessoaId");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nome");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoa");

                    b.HasData(
                        new
                        {
                            PessoaId = new Guid("e377f741-b75e-4fab-8a51-1af9c01a6a95"),
                            Email = "jose@gmail.com",
                            Nome = "jose"
                        },
                        new
                        {
                            PessoaId = new Guid("26f753a5-6ed9-45b0-95c1-9113148e6e1d"),
                            Email = "rodney@gmail.com",
                            Nome = "rodney"
                        });
                });

            modelBuilder.Entity("CadastroPessoaEndereco.PessoaAPI.Model.Endereco", b =>
                {
                    b.HasOne("CadastroPessoaEndereco.PessoaAPI.Model.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("CadastroPessoaEndereco.PessoaAPI.Model.Endereco", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("CadastroPessoaEndereco.PessoaAPI.Model.Pessoa", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
